# Tokenizer arguments
token_manager:
  _component_: torchtune.models.chameleon.chameleon_token_manager
  tokenizer_path: /tmp/chameleon-7b/tokenizer/text_tokenizer.json
  vqgan_cfg_path: /tmp/chameleon-7b/tokenizer/vqgan.yaml
  vqgan_ckpt_path: /tmp/chameleon-7b/tokenizer/vqgan.ckpt
  device: ${device}

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.chameleon.chameleon_7b

resume_from_checkpoint: False

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /tmp/chameleon-7b/
  checkpoint_files: [consolidated.pth]
  output_dir: /tmp/chameleon-7b/
  model_type: CHAMELEON

# Fine-tuning arguments
batch_size: 1
epochs: 3
optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: False

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /tmp/dalle-chameleon-finetune
log_every_n_steps: 1
log_peak_memory_stats: False
