ckpt_path: /tmp/TinyLlama-1.1B-Chat-v1.0


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /tmp/TinyLlama-1.1B-Chat-v1.0/tokenizer.model


# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  train_on_input: True
seed: null
shuffle: True


# Model Arguments
model:
  _component_: torchtune.models.llama2.tinyllama


checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpointer_dir: /tmp/TinyLlama-1.1B-Chat-v1.0
  checkpointer_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: /tmp/TinyLlama-1.1B-Chat-v1.0
  model_type: LLAMA2
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 3
optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
loss:
  _component_: torch.nn.CrossEntropyloss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: False

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /tmp/alpaca-tinyllama-finetune
log_every_n_steps: 1
log_peak_memory_stats: False
